spring.application.name=product-service

server.port=8081

# PostgreSQL - R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/products_db
spring.r2dbc.username=predeepkumar.s
spring.r2dbc.password=pred123

spring.sql.init.mode=always